[project]
name = "atividade-base-de-dados"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastexcel>=0.16.0",
    "plotly>=6.3.0",
    "polars>=1.33.1",
    "streamlit>=1.50.0",
]
